spring:
  application:
    name: gestaoTarefas

  datasource:
    url: jdbc:postgresql://localhost:5432/tarefas
    username: postgres
    password: 336313
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
